version: '1'
services:
  db:
    image: postgres:16
    container_name: db
    ports:
      - 5434:5432
    env_file: .env
    networks:
      - transcendence
  backend:
    image: backend
    container_name: backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    # restart: always
    env_file: .env
    networks:
      - transcendence
    ports:
      - "${BACKEND_PORT}:${BACKEND_PORT}"
    depends_on:
      - db
    links:
      - db
  frontend:
    image: frontend
    container_name: frontend
    build:
      context: ./front
      dockerfile: Dockerfile
    restart: always
    env_file: .env
    ports:
      - "${FRONTEND_PORT}:${FRONTEND_PORT}"
    networks:
      - transcendence
    depends_on:
      - backend
    # command: "npm run dev"
networks:
  transcendence:
